function matlab_cli_debug_smoke()
% Minimal smoke test for MATLAB -> Python CLI integration.
%
% Run from MATLAB:
%   matlab_cli_debug_smoke

    pyExe = '/opt/homebrew/bin/python3.11';
    baseDir = '/Users/adijain/ENGINEERING/IEOM/ieom_model';

    fprintf('Running health check...\n');
    [statusHealth, outHealth] = system(sprintf('cd %s && %s -m hesitation.inference.cli health', baseDir, pyExe));
    assert(statusHealth == 0, 'Health check failed: %s', outHealth);
    disp(outHealth);

    features = struct( ...
        'mean_hand_speed', 0.45, ...
        'pause_ratio', 0.15, ...
        'progress_delta', 0.75, ...
        'reversal_count', 1, ...
        'retry_count', 0, ...
        'task_step_id', 3, ...
        'human_robot_distance', 0.35 ...
    );

    cmd = sprintf([ ...
        'cd %s && %s -m hesitation.inference.cli predict ', ...
        '--mean-hand-speed %.6f --pause-ratio %.6f --progress-delta %.6f ', ...
        '--reversal-count %d --retry-count %d --task-step-id %d ', ...
        '--human-robot-distance %.6f --format json' ...
    ], ...
        baseDir, pyExe, ...
        features.mean_hand_speed, ...
        features.pause_ratio, ...
        features.progress_delta, ...
        int32(features.reversal_count), ...
        int32(features.retry_count), ...
        int32(features.task_step_id), ...
        features.human_robot_distance ...
    );

    [statusPred, outPred] = system(cmd);
    assert(statusPred == 0, 'Prediction failed: %s', outPred);
    prediction = jsondecode(outPred);

    required = {'state','state_probabilities','future_hesitation_prob','future_correction_prob','confidence'};
    for i = 1:numel(required)
        assert(isfield(prediction, required{i}), 'Missing field: %s', required{i});
    end

    fprintf('Smoke test passed.\n');
    fprintf('State: %s | Confidence: %.4f\n', prediction.state, prediction.confidence);
end
