function report = matlab_verify_three_scenarios()
% Verify three fixed scenarios for integration confidence.
%
% Returns a struct report and writes a .mat artifact.

    scenarios = {
        struct('name','normal_progress_like','mean_hand_speed',0.55,'pause_ratio',0.08,'progress_delta',0.82,'reversal_count',0,'retry_count',0,'task_step_id',2,'human_robot_distance',0.75), ...
        struct('name','hesitation_like','mean_hand_speed',0.07,'pause_ratio',0.72,'progress_delta',0.18,'reversal_count',2,'retry_count',1,'task_step_id',4,'human_robot_distance',0.33), ...
        struct('name','overlap_risk_like','mean_hand_speed',0.30,'pause_ratio',0.20,'progress_delta',0.48,'reversal_count',1,'retry_count',0,'task_step_id',5,'human_robot_distance',0.12)
    };

    rows = cell(size(scenarios));
    allPassed = true;
    for i = 1:numel(scenarios)
        s = scenarios{i};
        p1 = callPredict(s);
        p2 = callPredict(s);

        deterministic = strcmp(jsonencode(p1), jsonencode(p2));
        probs = struct2cell(p1.state_probabilities);
        pSum = sum(cellfun(@double, probs));
        validSum = abs(pSum - 1.0) <= 1e-6;
        validConf = p1.confidence >= 0.0 && p1.confidence <= 1.0;
        passed = deterministic && validSum && validConf;
        allPassed = allPassed && passed;

        rows{i} = struct( ...
            'scenario', s.name, ...
            'state', p1.state, ...
            'confidence', p1.confidence, ...
            'deterministic', deterministic, ...
            'prob_sum', pSum, ...
            'passed', passed ...
        );
    end

    report = struct();
    report.generated_at = datestr(now, 30);
    report.all_passed = allPassed;
    report.rows = [rows{:}];

    outDir = '/Users/adijain/ENGINEERING/IEOM/ieom_model/reports/phase3_verification';
    if ~exist(outDir, 'dir')
        mkdir(outDir);
    end
    save(fullfile(outDir, 'matlab_three_scenario_report.mat'), 'report');
end

function prediction = callPredict(features)
    pyExe = '/opt/homebrew/bin/python3.11';
    baseDir = '/Users/adijain/ENGINEERING/IEOM/ieom_model';
    cmd = sprintf([ ...
        'cd %s && %s -m hesitation.inference.cli predict ', ...
        '--mean-hand-speed %.6f --pause-ratio %.6f --progress-delta %.6f ', ...
        '--reversal-count %d --retry-count %d --task-step-id %d ', ...
        '--human-robot-distance %.6f --format json' ...
    ], ...
        baseDir, pyExe, ...
        features.mean_hand_speed, ...
        features.pause_ratio, ...
        features.progress_delta, ...
        int32(features.reversal_count), ...
        int32(features.retry_count), ...
        int32(features.task_step_id), ...
        features.human_robot_distance ...
    );
    [status, out] = system(cmd);
    assert(status == 0, 'Scenario prediction failed: %s', out);
    prediction = jsondecode(out);
end
